const REVENUE_REQUEST="REVENUE_REQUEST";
const REVENUE_REQUEST_SUCCESS="REVENUE_REQUEST_SUCCESS";
const REVENUE_REQUEST_FAILED="REVENUE_REQUEST_FAILED";

export {
	REVENUE_REQUEST,
	REVENUE_REQUEST_SUCCESS,
	REVENUE_REQUEST_FAILED
}