const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const USERNAME_NOT_FOUND = "USERNAME_NOT_FOUND";
const INCORRECT_PASSWORD = "INCORRECT_PASSWORD";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const LOGOUT_FAILED = "LOGOUT_FAILED";
const VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS";
const VERIFY_TOKEN_FAILED = "VERIFY_TOKEN_FAILED";

export {
	LOGIN_REQUEST,
	LOGIN_SUCCESS,
	USERNAME_NOT_FOUND,
	INCORRECT_PASSWORD,
 	LOGOUT_SUCCESS,
	LOGOUT_FAILED,
	VERIFY_TOKEN_SUCCESS,
	VERIFY_TOKEN_FAILED
}