const SEND_VERIFY_CODE_REQUEST="SEND_VERIFY_CODE_REQUEST";
const SEND_VERIFY_CODE_SUCCESS="SEND_VERIFY_CODE_SUCCESS";
const SEND_VERIFY_CODE_FAILED="SEND_VERIFY_CODE_FAILED";
const USER_NOT_FOUND="USER_NOT_FOUND";
const CODE_NOT_MATCHED="CODE_NOT_MATCHED";
const FORGOT_PASSWORD_REQUEST="FORGOT_PASSWORD_REQUEST";
const FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS";
const FORGOT_PASSWORD_FAILED="FORGOT_PASSWORD_FAILED";

export {
	SEND_VERIFY_CODE_REQUEST,
	SEND_VERIFY_CODE_SUCCESS,
	SEND_VERIFY_CODE_FAILED,
	FORGOT_PASSWORD_REQUEST,
	FORGOT_PASSWORD_SUCCESS,
	FORGOT_PASSWORD_FAILED,
	USER_NOT_FOUND,
	CODE_NOT_MATCHED
}