name: React Admin
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repo
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install node modules
        run: npm i
      - name: Set server API host name
        run: |
          touch .env
          echo REACT_APP_API_HOST=${{secrets.API_HOST}} > .env
      - name: Build app
        run: npm run build
      - name: FTP Upload
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_UNAME }}
          password: ${{ secrets.FTP_PASS }}
          localDir: "build"